-- AlterTable
ALTER TABLE "scale" ALTER COLUMN "weight_Individual" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "weight_total" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "scale_trend" ALTER COLUMN "weight" SET DATA TYPE DOUBLE PRECISION[];
