---
name: CI Full Tests
on: 
  push:
    branches: [ main, develop, release/** ]

jobs:
  test-all:
    uses: ./fresh-produce-inventory-tracker/.github/workflows/tests.yml
    with:
      test: 'full'
