---
name: CI Full Tests
on: 
  push:
    branches: [ main, develop, release/** ]

jobs:
  unit-tests:
    uses: ./.github/workflows/tests.yml
    with:
      test: 'full'
  integration-tests:
    uses: ./.github/workflows/main.yml
    with:
      test: 'full'
