name: unit-tests

on:
  workflow_call:
    inputs:
      test:
        description: 'Test being run (lint, unit, e2e, full)'
        required: true
        type: string
      type:
        description: 'type of test (affected, full)'
        required: false
        type: string
jobs:
  build:
    name: main-tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fresh-produce-inventory-tracker
    steps:
       
      - name: Checkout develop
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'main'

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install node
        run: npm install
        
      - name: Full Unit test 
        if: inputs.test == 'full' || inputs.test == 'unit'
        run: npx nx run-many --target=test --all --skip-nx-cache --parallel --coverage
        #working-directory: fresh-produce-inventory-tracker

