# This is a basic workflow to help you get started with Actions

name: main-tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main,develop ]
  pull_request:
    branches: [ main,develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup node"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: "Install Dependencies"
        working-directory: ./fresh-produce-inventory-tracker
        run: npm install

      - name: "Run tests"
        working-directory: ./fresh-produce-inventory-tracker
        run: npm test
      - name: Run the tests
        working-directory: ./fresh-produce-inventory-tracker
        run: npm test -- --coverage
      - name: Upload coverage to Codecov
      
        uses: codecov/codecov-action@v2
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            working-directory: ./fresh-produce-inventory-tracker
